Шпаргалка: основные операции/функции для матриц в NumPy
1) Создание

np.array([...]) — создаёт массив NumPy из списка/списков (матрица, если 2D).

np.zeros((m,n)) — матрица m×n из нулей.

np.ones((m,n)) — матрица m×n из единиц.

np.eye(n) — единичная матрица n×n (1 на диагонали).

np.arange(k) — числа 0..k-1 (часто для быстрых примеров).

np.linspace(a,b,n) — n равномерных чисел от a до b.

2) Форма и преобразования

A.shape — размеры массива (например (2,3)).

A.reshape(new_shape) — меняет форму без изменения данных (если кол-во элементов совпадает).

A.T — транспонирование 2D (строки↔столбцы).

np.transpose(A, axes=...) — перестановка осей (для тензоров/многомерных массивов).

np.expand_dims(A, axis=...) — добавляет новую ось размера 1 (полезно для broadcasting).

None / np.newaxis — короткий способ добавить ось в срезе (то же, что expand_dims).

4) Умножения

A * B — поэлементное умножение (одинаковые формы или broadcast).

A @ B — матричное умножение (линейная алгебра).

np.matmul(A, B) — то же, что @ (ещё умеет batch-умножение).

np.dot(A, B) — “dot”: для 1D скалярное, для 2D похоже на матричное, для >2D есть нюансы.

np.einsum("ij,jk->ik", A, B) — гибкое умножение/свёртки по заданным индексам (универсальный инструмент).

5) Суммы/агрегации по осям

np.sum(A, axis=..., keepdims=...) — сумма по оси (строки/столбцы), keepdims сохраняет размерность.

np.mean(A, axis=...) — среднее по оси.

np.max(A, axis=...) — максимум по оси.

np.min(A, axis=...) — минимум по оси.

6) Линейная алгебра (если понадобится)

np.linalg.inv(A) — обратная матрица (если существует).

np.linalg.solve(A, b) — решает систему A x = b (обычно лучше/стабильнее, чем inv).

np.linalg.det(A) — определитель матрицы.

np.linalg.norm(A) — норма (длина/размер) матрицы/вектора (по умолчанию Фробениус для матриц).

Шпаргалка: основные операции/функции для тензеров в NumPy
1) Формы и оси

x.shape — размеры тензора (например (2, 3, 4)).

x.ndim — сколько осей (размерность): 1D/2D/3D/…

x.size — сколько всего элементов (произведение размеров).

x.reshape(...) — меняет форму тензора (числа те же), если количество элементов совпадает.

2) Добавление/удаление осей

x[..., None] — добавляет ось размера 1 в конец (например (2,3) → (2,3,1)).

x[:, None, :] — добавляет ось размера 1 в середину (например (N,D) → (N,1,D)).

np.expand_dims(x, axis=k) — то же самое: вставляет новую ось размера 1 в позицию k.

np.squeeze(x, axis=...) — убирает оси размера 1 (например (2,1,3) → (2,3)).

3) Перестановка осей

x.transpose(...) — меняет порядок осей (например (2,3,4) → (3,2,4)).

np.transpose(x, axes=...) — то же, но явно задаёшь порядок осей.

np.swapaxes(x, a, b) — меняет местами две оси a и b.

x.T — “короткое” транспонирование; удобно для 2D, для тензоров работает как частный случай перестановки осей (часто не так явно, лучше transpose).

4) Суммы/средние/максимумы по осям

np.sum(x, axis=..., keepdims=True/False) — суммирует по выбранной оси; keepdims=True оставляет ось размером 1 для broadcasting.

np.mean(x, axis=..., keepdims=...) — среднее по оси.

np.max(x, axis=..., keepdims=...) — максимум по оси.

5) Умножения

x * y — поэлементное умножение (с одинаковыми формами или через broadcasting).

x @ y — тензорное “матричное” умножение (batch matmul): умножает последние 2 оси как матрицы, остальные считаются batch-осями.

np.matmul(x, y) — то же, что @ (официальная функция).

np.dot(x, y) — dot с историческими правилами; для тензоров может вести себя неожиданно, чаще предпочитают matmul/einsum.

np.einsum("...ij,...jk->...ik", A, B) — универсальная операция по индексам: можно задавать, какие оси перемножать/суммировать (очень гибко).

6) Broadcasting — типовые приёмы

keepdims=True — сохраняет ось (размер 1) после агрегации, чтобы потом легко делить/вычитать с broadcasting.

None (или np.newaxis) — быстрый способ добавить ось размера 1 в нужном месте, чтобы формы стали совместимы.

примеры от гпт:

In [ ]:
# Пример 1 — обычное матричное умножение (2D @ 2D)
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])      # shape (2, 3)

B = np.array([[10, 20],
              [30, 40],
              [50, 60]])       # shape (3, 2)

C = A @ B                      # shape (2, 2)
print(C)

[[220 280]
 [490 640]]


In [ ]:
# Пример 2 — разница между * и @
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[10, 20],
              [30, 40]])

print("A * B (поэлементно):\n", A * B)
print("A @ B (матрично):\n", A @ B)

A * B (поэлементно):
 [[ 10  40]
 [ 90 160]]
A @ B (матрично):
 [[ 70 100]
 [150 220]]


In [1]:
#Пример 3 — “батч” умножение + broadcasting (3D @ 2D)
import numpy as np

batch = np.arange(2*2*3).reshape(2, 2, 3)  # shape (2, 2, 3) — 2 матрицы 2x3
M = np.array([[1, 0],
              [0, 1],
              [1, 1]])                     # shape (3, 2)

result = batch @ M                         # shape (2, 2, 2)
print("batch shape:", batch.shape)
print(batch)
print("M shape:", M.shape)
print("result shape:", result.shape)
print(result)


batch shape: (2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
M shape: (3, 2)
result shape: (2, 2, 2)
[[[ 2  3]
  [ 8  9]]

 [[14 15]
  [20 21]]]


In [ ]:
# доп пример с тензером
import numpy as np

a = np.arange(12)
print("a:", a)
print("a.shape:", a.shape)

batch = a.reshape(2,2,3) #batch = tensor
print("batch:\n", batch)
print("batch.shape:", batch.shape)

print("batch[0]:\n", batch[0])
print("batch[1]:\n", batch[1])

a: [ 0  1  2  3  4  5  6  7  8  9 10 11]
a.shape: (12,)
batch:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
batch.shape: (2, 2, 3)
batch[0]:
 [[0 1 2]
 [3 4 5]]
batch[1]:
 [[ 6  7  8]
 [ 9 10 11]]


In [ ]:
# Пример 4 — Batch-матричное умножение (3D @ 2D)
import numpy as np

# 4 матрицы 2x3 (batch=4)
X = np.arange(4*2*3).reshape(4, 2, 3)   # shape (4, 2, 3)

# матрица 3x5
W = np.arange(3*5).reshape(3, 5)        # shape (3, 5)

Y = X @ W                                # shape (4, 2, 5)

print("X shape:", X.shape)
print("Тензер 4*2*3(матрицы из 4 матриц), X:\n", X)
print("W shape:", W.shape)
print("Матрица 3*5, W:\n", W)
print("Y shape:", Y.shape)
print("Y:\n", Y)
print("Первый элемент в тезере\n",Y[0])  # покажем результат для первой матрицы в батче

X shape: (4, 2, 3)
Тензер 4*2*3(матрицы из 4 матриц), X:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
W shape: (3, 5)
Матрица 3*5, W:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Y shape: (4, 2, 5)
Y:
 [[[ 25  28  31  34  37]
  [ 70  82  94 106 118]]

 [[115 136 157 178 199]
  [160 190 220 250 280]]

 [[205 244 283 322 361]
  [250 298 346 394 442]]

 [[295 352 409 466 523]
  [340 406 472 538 604]]]
Первый элемент в тезере
 [[ 25  28  31  34  37]
 [ 70  82  94 106 118]]


In [ ]:
# Пример 2 — Broadcasting на 3D тензоре (нормализация по последней оси)
import numpy as np

X = np.random.rand(2, 3, 4)  # shape (2,3,4)

# хотим, чтобы суммы по последней оси стали 1 (как "вероятности")
S = X.sum(axis=2, keepdims=True)  # shape (2,3,1)
X_norm = X / S                    # broadcasting: (2,3,4) / (2,3,1) -> (2,3,4)

print("X shape:", X.shape)
print(X)
print("S shape:", S.shape)
print(S)
print("X_norm shape:", X_norm.shape)
print("check sums:", X_norm.sum(axis=2))  # должно быть близко к 1


X shape: (2, 3, 4)
[[[0.89168588 0.40934579 0.32446599 0.23705857]
  [0.28796953 0.9878709  0.88737844 0.49464319]
  [0.31395271 0.19718576 0.86703906 0.28759312]]

 [[0.04846787 0.48696901 0.24584061 0.51520604]
  [0.37208096 0.21893309 0.5221649  0.01721248]
  [0.83681732 0.37950388 0.83313581 0.09116225]]]
S shape: (2, 3, 1)
[[[1.86255622]
  [2.65786206]
  [1.66577066]]

 [[1.29648354]
  [1.13039143]
  [2.14061926]]]
X_norm shape: (2, 3, 4)
check sums: [[1. 1. 1.]
 [1. 1. 1.]]


Практика: придуманные задания от гпт 

Создай матрицу A размера (3,4) из arange и матрицу B размера (4,2). Найди A @ B.

In [10]:
import numpy as np
A = np.arange(3*4).reshape(3,4)
B = np.arange(4*2).reshape(4,2)
C = np.matmul(A,B)
print("A:\n ", A)
print("B:\n ", B)
print("A@B:\n ", A@B)
print("Shape:\n ", C.shape)


A:
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
B:
  [[0 1]
 [2 3]
 [4 5]
 [6 7]]
A@B:
  [[ 28  34]
 [ 76  98]
 [124 162]]
Shape:
  (3, 2)


Сделай матрицу X (5,3) и вектор весов w (3,). Посчитай y = X @ w. Выведи y.shape.

In [11]:
import numpy as np
X = np.random.rand(5,3)
W = np.random.rand(3,)
y = X @ W

print(y)
print(y.shape)

[0.78981992 1.29601242 0.7386449  0.8634735  1.4133217 ]
(5,)


Создай A (2,3) и B (2,3). Посчитай:

поэлементно A*B

сумму всех элементов результата

In [34]:
import numpy as np
A = np.arange(2*3).reshape(2,3)
B = np.arange(2*3).reshape(2,3)

print(A*B)

[[ 0  1  4]
 [ 9 16 25]]


Создай матрицу A (3,3). Найди A.T и проверь, что (A.T).T == A.

In [37]:
import numpy as np
A = np.arange(3*3).reshape(3,3)
k = False
if ((A.T).T).all() == (A).all():
    k = True 
print(k)
print("A:\n ", A)
print("A.T:\n ", A.T)
print("(A.T).T:\n ", (A.T).T)

True
A:
  [[0 1 2]
 [3 4 5]
 [6 7 8]]
A.T:
  [[0 3 6]
 [1 4 7]
 [2 5 8]]
(A.T).T:
  [[0 1 2]
 [3 4 5]
 [6 7 8]]


Сделай матрицу X (4,5). Посчитай суммы:

по строкам (axis=1)

по столбцам (axis=0)

In [39]:
import numpy as np
X = np.arange(20).reshape(4,5)
S_line = np.sum(X, axis = 1, keepdims= True)
S_column = np.sum(X, axis = 0, keepdims= True)
print("X:\n ", X)
print("S_line:\n ", S_line)
print("S_column:\n ", S_column)

X:
  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
S_line:
  [[10]
 [35]
 [60]
 [85]]
S_column:
  [[30 34 38 42 46]]


Broadcasting: матрица X (4,3) и вектор b (3,). Посчитай X + b. Объясни почему работает.

In [40]:
import numpy as np
X = np.arange(12).reshape(4,3)
b = np.arange(3)
print("X:\n ", X)
print("b:\n ", b)
print("X+b:\n ", X + b)

X:
  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
b:
  [0 1 2]
X+b:
  [[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


Broadcasting: матрица X (4,3). Сделай “нормализацию по строкам”:
X_norm = X / X.sum(axis=1, keepdims=True)
Проверь, что суммы строк стали 1.

In [44]:
import numpy as np
X = np.arange(12).reshape(4,3)
X_norm = X / X.sum(axis=1, keepdims=True)
k = False
if (np.sum(X_norm, axis=1, keepdims=True)).all() == 1:
    k = True 
print(k)
print("X:\n ", X)
print("X_norm:\n ", X_norm)
print("X_norm_sum:\n ", X_norm.sum(axis=1))

True
X:
  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
X_norm:
  [[0.         0.33333333 0.66666667]
 [0.25       0.33333333 0.41666667]
 [0.28571429 0.33333333 0.38095238]
 [0.3        0.33333333 0.36666667]]
X_norm_sum:
  [1. 1. 1. 1.]


Сделай A (3,1) и B (1,4). Посчитай A + B и объясни форму результата.

In [45]:
import numpy as np 
A = np.arange(3).reshape(3,1)
B = np.arange(4).reshape(1,4)
print("A:\n ", A)
print("B:\n ", B)
print("A+B:\n ", A+B)

A:
  [[0]
 [1]
 [2]]
B:
  [[0 1 2 3]]
A+B:
  [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


Батч-умножение: сделай batch формы (10, 2, 3) и матрицу M формы (3,4). Посчитай batch @ M и напиши форму результата.

In [48]:
import numpy as np

batch = np.arange(10*2*3).reshape(10,2,3)
M = np.arange(12).reshape(3,4)
C = np.matmul(batch,M)
print("batch:\n ", batch[0])
print("M:\n ", M)
print("C:\n ", C)

batch:
  [[0 1 2]
 [3 4 5]]
M:
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
C:
  [[[  20   23   26   29]
  [  56   68   80   92]]

 [[  92  113  134  155]
  [ 128  158  188  218]]

 [[ 164  203  242  281]
  [ 200  248  296  344]]

 [[ 236  293  350  407]
  [ 272  338  404  470]]

 [[ 308  383  458  533]
  [ 344  428  512  596]]

 [[ 380  473  566  659]
  [ 416  518  620  722]]

 [[ 452  563  674  785]
  [ 488  608  728  848]]

 [[ 524  653  782  911]
  [ 560  698  836  974]]

 [[ 596  743  890 1037]
  [ 632  788  944 1100]]

 [[ 668  833  998 1163]
  [ 704  878 1052 1226]]]


Сделай матрицу X (6,2) — точки на плоскости. Посчитай попарные разности X[:, None, :] - X[None, :, :] и объясни форму (6,6,2). (Это супер-полезный пример broadcasting.)

In [50]:
import numpy as np
X = np.arange(12).reshape(6,2)
D = X[:, None, :] - X[None, :, :]
print("X:\n ", X)
print("D:\n ", D)
print("D.shape:\n ", D.shape)

X:
  [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
D:
  [[[  0   0]
  [ -2  -2]
  [ -4  -4]
  [ -6  -6]
  [ -8  -8]
  [-10 -10]]

 [[  2   2]
  [  0   0]
  [ -2  -2]
  [ -4  -4]
  [ -6  -6]
  [ -8  -8]]

 [[  4   4]
  [  2   2]
  [  0   0]
  [ -2  -2]
  [ -4  -4]
  [ -6  -6]]

 [[  6   6]
  [  4   4]
  [  2   2]
  [  0   0]
  [ -2  -2]
  [ -4  -4]]

 [[  8   8]
  [  6   6]
  [  4   4]
  [  2   2]
  [  0   0]
  [ -2  -2]]

 [[ 10  10]
  [  8   8]
  [  6   6]
  [  4   4]
  [  2   2]
  [  0   0]]]
D.shape:
  (6, 6, 2)


ТЕНЗЕРЫ 

A. Формы, оси, reshape (база)

Создай тензор T из np.arange(2*3*4) формы (2,3,4).
Выведи: T.shape, T[0].shape, T[:, :, 0].shape.

In [ ]:
import numpy as np
T = np.arange(2*3*4).reshape(2,3,4)
print("T.shape:\n ", T.shape)
print("T[0].shape:\n ", T[0].shape)
print("T[0]:\n ", T[0])
print("TT[:, :, 0].shape:\n ", T[:, :, 0].shape)


T.shape:
  (2, 3, 4)
T[0].shape:
  (3, 4)
T[0]:
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
TT[:, :, 0].shape:
  (2, 3)


Сделай T.reshape(6,4) и T.reshape(2,12). Объясни, почему это возможно.

In [56]:
import numpy as np
T = np.arange(24).reshape(6,4)
M = np.arange(24).reshape(2,12)

print("T[0]:\n ", T[0])
print("M[0]:\n ", M[0])

T[0]:
  [0 1 2 3]
M[0]:
  [ 0  1  2  3  4  5  6  7  8  9 10 11]


Для тензора (2,3,4) посчитай:

сумму по axis=0, axis=1, axis=2

и везде проверь формы результата

In [ ]:
import numpy as np
T = np.arange(2*3*4).reshape(2,3,4)
S_0 = np.sum(T, axis=0, keepdims=True)
S_1 = np.sum(T, axis=1, keepdims=True)
S_2 = np.sum(T, axis=2, keepdims=True)

print('T[0]:\n ', T[0])
print('S_0:\n ', S_0) 
print('S_1:\n ', S_1) 
print('S_2:\n ', S_2) 

T[0]:
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
S_0:
  [[[12 14 16 18]
  [20 22 24 26]
  [28 30 32 34]]]
S_1:
  [[[12 15 18 21]]

 [[48 51 54 57]]]
S_2:
  [[[ 6]
  [22]
  [38]]

 [[54]
  [70]
  [86]]]


Дан T формы (2,3,4). Получи “срез” второй матрицы из batch и второй строки: T[1, 1, :] и объясни форму.

In [61]:
import numpy as np
T = np.arange(2*3*4).reshape(2,3,4)
S = T[1, 1, :]
print('T[0]:\n ', T[1])
print('S:\n ', S)

T[0]:
  [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
S:
  [16 17 18 19]


B. Broadcasting (обязательно)

X формы (5, 10, 3) и b формы (3,). Сделай X + b.
Объясни, к чему прибавился b.

In [ ]:
import numpy as np
X = np.arange(5*10*3).reshape(5,10,3)
b = np.arange(3)
print("X[0]:\n ", X[0])
print("b:\n ", b)
print("X+b:\n ", X + b)

X[0]:
  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
b:
  [0 1 2]
X+b:
  [[[  0   2   4]
  [  3   5   7]
  [  6   8  10]
  [  9  11  13]
  [ 12  14  16]
  [ 15  17  19]
  [ 18  20  22]
  [ 21  23  25]
  [ 24  26  28]
  [ 27  29  31]]

 [[ 30  32  34]
  [ 33  35  37]
  [ 36  38  40]
  [ 39  41  43]
  [ 42  44  46]
  [ 45  47  49]
  [ 48  50  52]
  [ 51  53  55]
  [ 54  56  58]
  [ 57  59  61]]

 [[ 60  62  64]
  [ 63  65  67]
  [ 66  68  70]
  [ 69  71  73]
  [ 72  74  76]
  [ 75  77  79]
  [ 78  80  82]
  [ 81  83  85]
  [ 84  86  88]
  [ 87  89  91]]

 [[ 90  92  94]
  [ 93  95  97]
  [ 96  98 100]
  [ 99 101 103]
  [102 104 106]
  [105 107 109]
  [108 110 112]
  [111 113 115]
  [114 116 118]
  [117 119 121]]

 [[120 122 124]
  [123 125 127]
  [126 128 130]
  [129 131 133]
  [132 134 136]
  [135 137 139]
  [138 140 142]
  [141 143 145]
  [144 146 148]
  [147 149 151]]]


X формы (5, 10, 3). Сделай тензор scale формы (10,1) и примени масштабирование по “средней оси”:
Подсказка: сначала приведи scale к форме, совместимой с X.

Нормализуй X формы (2,3,4) по последней оси так, чтобы суммы по последней оси стали 1.
(Как в примере 2, но сделай самостоятельно и проверь.)

Сделай тензор X формы (4,6) и вектор w формы (4,).
Добейся умножения “по строкам” (чтобы каждая строка умножилась на свой вес).
Подсказка: подумай, где нужно добавить ось None.

C. Умножение тензоров (batch matmul)

A формы (8, 2, 3), B формы (8, 3, 4). Посчитай A @ B и проверь форму результата.

A формы (8, 2, 3) и W формы (3, 4). Посчитай A @ W.
Объясни, почему NumPy “применил” W ко всем 8 матрицам.

Сделай “двухслойное” преобразование:
X формы (batch=5, features=10)
W1 (10, 7), W2 (7, 3)
Посчитай Y = X @ W1 @ W2 и проверь форму.

D. Transpose и перестановка осей

T формы (2,3,4). Получи T_perm формы (3,2,4) с помощью transpose/swapaxes.
Проверь, что данные те же, только оси переставлены.

Сделай T формы (2,3,4,5). Переставь оси так, чтобы получилось (2,4,3,5).

E. Практичные мини-задачи (похоже на ML/компьютерное зрение)

Представь, что images формы (batch=16, height=32, width=32, channels=3).
Посчитай среднее по каналам (получить “серое изображение”) → форма должна стать (16,32,32).

Дан scores формы (batch=6, classes=10).
Вычисли softmax по оси classes (стабильно):

вычти максимум по строке

применить exp

поделить на сумму exp
Проверь, что суммы по классам = 1.